"""Generated image disclosure and metadata stamping."""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any
import json


@dataclass
class GenerationMetadata:
    """Metadata for generated images."""

    generated_at: datetime = field(default_factory=datetime.utcnow)
    generator_name: str = ""
    generator_version: str = ""
    input_hash: str = ""
    parameters: dict[str, Any] = field(default_factory=dict)
    disclosure: str = "This image was generated by AI"

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at.isoformat(),
            "generator": f"{self.generator_name}:{self.generator_version}",
            "input_hash": self.input_hash,
            "parameters": self.parameters,
            "disclosure": self.disclosure,
        }


def stamp_generated(
    image_path: Path,
    metadata: GenerationMetadata,
    create_sidecar: bool = True,
) -> Path:
    """
    Create sidecar metadata file for generated image.

    Args:
        image_path: Path to output image
        metadata: Generation metadata
        create_sidecar: Whether to create JSON sidecar

    Returns:
        Path to sidecar file
    """
    if create_sidecar:
        sidecar_path = image_path.with_suffix(".generated.json")
        with open(sidecar_path, "w") as f:
            json.dump(metadata.to_dict(), f, indent=2)
        return sidecar_path
    return image_path
