# Copyright (c) 2025 Skolyn LLC. All rights reserved.
# SPDX-License-Identifier: EUPL-1.1

"""
Explanation Templates
=====================

Prompt templates for finding explanations with MedGemma.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


EXPLANATION_SYSTEM_PROMPT = """You are an expert radiologist assistant providing explanations 
for AI-detected findings. Your explanations must:
- Be evidence-based and reference clinical guidelines when appropriate
- Clearly explain the reasoning behind the finding
- Acknowledge limitations and uncertainty
- Suggest appropriate follow-up when indicated
- Be understandable to clinical users while maintaining technical accuracy

Always emphasize that AI findings are for decision support only."""


@dataclass
class ExplanationTemplate:
    """Template for finding explanations."""
    name: str
    system_prompt: str
    user_prompt_template: str


GENERAL_FINDING_TEMPLATE = ExplanationTemplate(
    name="general_finding",
    system_prompt=EXPLANATION_SYSTEM_PROMPT,
    user_prompt_template="""Explain the following AI-detected finding:

FINDING: {finding_description}
LOCATION: {location}
CONFIDENCE: {confidence}
SEVERITY: {severity}

SUPPORTING EVIDENCE:
- Measurements: {measurements}
- Visual features: {visual_features}

Please provide:
1. A clear explanation of what was detected
2. Why this finding is clinically relevant
3. Potential differential diagnoses
4. Recommended follow-up or additional imaging
5. Limitations of the AI analysis

Be specific about uncertainty in the analysis.""",
)


LESION_EXPLANATION_TEMPLATE = ExplanationTemplate(
    name="lesion_explanation",
    system_prompt=EXPLANATION_SYSTEM_PROMPT,
    user_prompt_template="""Explain this lesion detection:

LESION TYPE: {lesion_type}
LOCATION: {location}
SIZE: {size}
CHARACTERISTICS: {characteristics}
CONFIDENCE: {confidence}

Provide:
1. Description of the lesion appearance
2. Differential diagnosis considerations
3. Relevant clinical guidelines (e.g., BI-RADS, PI-RADS, Lung-RADS)
4. Recommended management
5. Limitations and areas requiring human review""",
)


UNCERTAINTY_DISCLAIMER_TEMPLATE = """
IMPORTANT DISCLAIMER:
This analysis was generated by an AI system and is intended for clinical decision 
support only. All findings require verification by a qualified radiologist before 
clinical use. The AI may have limitations in detecting certain pathologies and 
may produce false positive or false negative results. Model confidence: {confidence}.
"""


def format_explanation_prompt(
    template: ExplanationTemplate,
    finding_data: dict[str, Any],
) -> str:
    """Format explanation prompt with finding data."""
    import re
    placeholders = re.findall(r'\{(\w+)\}', template.user_prompt_template)
    filled = {k: finding_data.get(k, "Not available") for k in placeholders}
    return template.user_prompt_template.format(**filled)


def get_disclaimer(confidence: float) -> str:
    """Get formatted uncertainty disclaimer."""
    return UNCERTAINTY_DISCLAIMER_TEMPLATE.format(confidence=f"{confidence:.1%}")
